import { NextResponse } from 'next/server';
import Replicate from 'replicate';

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

export async function POST(request: Request) {
  const body = await request.json();
  console.log('Received request body:', body);

  const { prompt, aspectRatio, numOutputs, outputQuality, numInferenceSteps, disableSafetyChecker, userId } = body;

  try {
    console.log('Calling Replicate API with:', { prompt, aspectRatio, numOutputs, outputQuality, numInferenceSteps, disableSafetyChecker });
    const output = await replicate.run(
      "paresh795/mukul-img-gen:d965dcd22a46b22b8f3c3a55629f436c9adff779628fdcf303b0e5eb96e4b35e",
      {
        input: {
          prompt,
          aspect_ratio: aspectRatio,
          model: "dev",
          lora_scale: 1,
          num_outputs: numOutputs,
          output_format: "webp",
          guidance_scale: 3.5,
          output_quality: outputQuality,
          prompt_strength: 0.8,
          extra_lora_scale: 1,
          num_inference_steps: numInferenceSteps,
          disable_safety_checker: disableSafetyChecker
        }
      }
    );
    console.log('Replicate API output:', output);
    if (Array.isArray(output) && output.length > 0) {
      console.log('Returning image URLs:', output);
      return NextResponse.json({ success: true, imageUrls: output });
    } else {
      console.log('No images generated by Replicate API');
      throw new Error('No images generated');
    }
  } catch (error) {
    console.error('Error in API route:', error);
    return NextResponse.json({ success: false, error: 'Failed to generate image' }, { status: 500 });
  }
}
