// utils/examplePrompts.ts

export const examplePrompts = [
  "mukulsharma as a futuristic astronaut exploring Mars",
  "Portrait of mukulsharma as a Renaissance era nobleman",
  "mukulsharma performing a daring skydive over the Grand Canyon",
  "mukulsharma as a Jedi Knight wielding a lightsaber",
  "Cyberpunk version of mukulsharma in a neon-lit city",
  "mukulsharma as a famous chef in a professional kitchen",
  "Superhero mukulsharma flying through a cityscape",
  "mukulsharma as a medieval knight in shining armor",
  "Close-up of mukulsharma as a wise old wizard",
  "mukulsharma as an Olympic athlete winning a gold medal",
  "Steampunk inventor mukulsharma with a complex contraption",
  "mukulsharma as a rock star performing on a huge stage",
  "Detective mukulsharma in a film noir setting",
  "mukulsharma as a deep-sea explorer in a futuristic submarine",
  "Tribal chief mukulsharma in traditional attire",
  "mukulsharma as a Formula 1 race car driver",
  "Adventurer mukulsharma discovering an ancient temple",
  "mukulsharma as a samurai warrior in feudal Japan",
  "Futuristic CEO mukulsharma in a high-tech office",
  "mukulsharma as a world-famous painter in an art studio",
  "Pirate captain mukulsharma on a ship's deck",
  "mukulsharma as a time traveler in different historical eras",
  "Firefighter mukulsharma rescuing people from a burning building",
  "mukulsharma as a Sherlock Holmes-style detective",
  "Astronomer mukulsharma observing stars through a telescope",
  "mukulsharma as a martial arts master in a dojo",
  "Wildlife photographer mukulsharma on safari",
  "mukulsharma as a Viking warrior on a longship",
  "Surfer mukulsharma riding a massive wave",
  "mukulsharma as a mad scientist in a laboratory",
   // Sports-related prompts
   "mukulsharma hitting a winning six in a cricket World Cup final",
   "mukulsharma lifting the FIFA World Cup trophy as team captain",
   "mukulsharma performing a spectacular diving catch in a Test match",
   "mukulsharma scoring a bicycle kick goal in a Champions League final",
   "mukulsharma as a cricket commentator in the broadcasting box",
   "mukulsharma bowling a perfect yorker in a T20 match",
   "mukulsharma celebrating a hat-trick in an Ashes series",
   "mukulsharma as a football manager giving a tactical talk",
   "mukulsharma receiving a Man of the Match award in an IPL final",
   "mukulsharma executing a perfect free-kick over a defensive wall",
   "mukulsharma as a sports analyst on a popular TV show",
   "mukulsharma playing a cover drive in classical cricket whites",
   
   // More diverse scenarios
   "mukulsharma as a space tourist floating in zero gravity",
   "mukulsharma giving a TED talk on stage",
   "mukulsharma as a wildlife photographer capturing a rare species",
   "mukulsharma conducting a symphony orchestra",
   "mukulsharma as a Michelin-starred chef plating a gourmet dish",
   "mukulsharma receiving a Nobel Prize in Stockholm",
   "mukulsharma as a cutting-edge robotics engineer",
   "mukulsharma performing a magic trick on a Las Vegas stage",
   "mukulsharma as a fashion designer at Paris Fashion Week",
   "mukulsharma exploring an ancient temple as an archaeologist",
   "mukulsharma as a Formula 1 driver on the podium",
   "mukulsharma performing a classical Indian dance",
   "mukulsharma as a news anchor reporting breaking news",
   "mukulsharma scuba diving in the Great Barrier Reef",
   "mukulsharma as a chess grandmaster in deep concentration",
   "mukulsharma piloting a fighter jet",
   "mukulsharma as a neurosurgeon performing a complex operation",
   "mukulsharma leading a mountain expedition to Everest",
   "mukulsharma as a UN ambassador giving a speech",
   "mukulsharma in a zero-gravity spacewalk outside the ISS",
   "mukulsharma as a virtual reality game designer",
   "mukulsharma conducting a groundbreaking scientific experiment",
   "mukulsharma as a Bollywood star in an elaborate dance number",
   "mukulsharma receiving an Oscar at the Academy Awards"
];